### ISSUE TITLE
Issue on menu "active" offset position is set

### ISSUE THREAD

**Issue by claudchan** [kswedberg/jquery-smooth-scroll#101]
Hi,
I have set offset value in the option. I notice that on scrolling the page, the menu "active" is not highlighted as per offset value.

Example if I set offset is -100, on page scrolling to next section, the menu still active in the previous one until if the section top is match zero of window top then only get active.

The menu should be active by -100 not zero when on page scrolling.

**Comment by kswedberg** [comment]
I'm not sure I understand what you're trying to do. This plugin doesn't automatically set active state on menu items. It doesn't react to scrolling, really. It just performs the scrolling in a smooth way (rather than "jumping" from one scroll position to another). I can try to help if you set up a demonstration of the problem somewhere — on a public site or jsbin.com or jsfiddle.net or codepen.io or something.

**Comment by claudchan** [comment]
So sorry, my fault. Is my bootstrap framwork did it. Scrollspy.
Thanks.
