### ISSUE TITLE
Focus element that has been scrolled to

### ISSUE THREAD

**Issue by fschroiff** [kswedberg/jquery-smooth-scroll#67]
This is an accessibility measure. Scrolling without focussing can cause issues when tabbing through links on a page. You smooth-scroll to an anchor way down on the page, but the focus stays on the very first element. Then you tab to the next thing expecting it to take you to the next visible link, but it whips you back up to the very first element.

**Comment by kswedberg** [comment]
Updated docs.

**Comment by diegocanal** [comment]
A very interesting article about this matter [https://css-tricks.com/smooth-scrolling-accessibility/](https://css-tricks.com/smooth-scrolling-accessibility/)

**Comment by kswedberg** [comment]
thanks @diegocanal ! I just published version 2.2.0 to include an `autoFocus` option. Its default is currently `false`, because otherwise it would be a "breaking change" and I'm trying to be good about "semver" versioning. I'm also going to publish version 3.0.0 soon, which will have `autoFocus` default to `true`.
