### ISSUE TITLE
Set hash in location bar

### ISSUE THREAD

**Issue by dobesv** [kswedberg/jquery-smooth-scroll#78]
Currently when it smooth scrolls to an anchor, the hash isn't set in the URL bar.

**Comment by kswedberg** [comment]
Here's an example of it working with hash-change support:
https://kswedberg.github.io/jquery-smooth-scroll/demo/bbq.html

**Comment by richgcook** [comment]
Does anyone know if there's an alternative to BBQ for jQuery 1.9+ as $.browser was removed in jQuery 1.9?

**Comment by kswedberg** [comment]
Not sure, but you could add a line to a script before you include the bbq plugin (if you don't need to support IE 6 or 7):

```$.browser = {msie: false};```

**Comment by kswedberg** [comment]
For people looking at this issue in the future, you can use the `hashchange` event without jQuery BBQ, too, if you don't need support for IE < 9. Here is a demo: https://kswedberg.github.io/jquery-smooth-scroll/demo/hashchange.html

**Comment by luisspuerto** [comment]
@kswedberg your last example script works great!! thanks!! However, doesn't make footnotes backlinks behave correctly. At least if you are using bigfoot.js. I haven't tried without. Do you know could be the reason?

**Comment by kswedberg** [comment]
@luisspuerto , I'm not familiar with bigfoot.js, and I'm not sure what exactly you're trying to do, but if you provide the URL of a page that demonstrates the problem, I can try to take a look. At the bigfoot.js page, it looks like the purpose of that plugin is to show footnotes _in place_ so you don't have to scroll back and forth, so I'm confused about why it would be relevant. Anyway, any additional info, or ideally a demo, would help me to help you.

**Comment by luisspuerto** [comment]
hey @kswedberg sorry for the delay in the reply. You can see an example here. 

https://luisspuerto.github.io/luisspuerto.net-testing/blog/2018/07/23/new-web-in-jekyll/

if you use the hash to the second footnote https://luisspuerto.github.io/luisspuerto.net-testing/blog/2018/07/23/new-web-in-jekyll/#/fnref:2 you are pointed to the top of the site. 

It's true that bigfoot.js can hide the footnotes completely, but it allow to show at the bottom of the post through options, which I like. Thus the problem.

**Comment by luisspuerto** [comment]
PS/ @kswedberg I just tried without bigfoot and the behavior is the same... first click ti goes to the top the page. Second click positions correctly.

**Comment by kswedberg** [comment]
ok, thanks, @luisspuerto. I'm looking into it now.

**Comment by kswedberg** [comment]
Hi @luisspuerto , there are two problems here. The first is that the selector you're using for the `scrollTarget` value is not a valid css identifier, so the plugin is unable to locate the element in the DOM. To fix that, you can either use `CSS.escape()` with an optional polyfill or just escape it yourself with a regular expression replace. Since we know that the invalid character is ":", you can just add another `.replace()` call in the `hashchange` handler. Something like this: `var target = location.hash.replace(/^\#\/?/,'#').replace(/\:/g, '\\:');` See https://api.jquery.com/category/selectors/ for more information.

I noticed that you have `$('a').smoothScroll({offset: -80});` in addition to the other call to `$.smoothScroll()` in the `hashchange` handler. You really should only have one or the other, so you can safely remove the first one, especially since it doesn't account for the first problem noted above. Keep in mind, however, that if you have the `$.smoothScroll()` call in hashchange instead of in the click handler, you may run into another problem. If you click the link the first time, it will scroll to the correct position the first time, but then if you scroll back down manually and click the link again, it will not scroll. The hash already changed the first time, so the second time the hashchange event will not be triggered. 

Hope that all makes sense.

**Comment by luisspuerto** [comment]
@kswedberg Thanks a lot for your help and for the time you invested in solve my question! I'll try to implement it this way. 

Thanks a lot!

**Comment by kswedberg** [comment]
You're welcome! Let me know if you still have problems with this.
