### ISSUE TITLE
Is the autoCoefficient option working fine?

### ISSUE THREAD

**Issue by diegocanal** [kswedberg/jquery-smooth-scroll#79]
Hi,
I have the impression that, when using speed: 'auto', changing the value of autoCoefficient does not take effect, I have tried with 1, 2, 20 and 100. Could anybody confirm this please?

Regards,

**Comment by kswedberg** [comment]
Works fine for me. I clicked the "p5" link at https://kswedberg.github.io/jquery-smooth-scroll/demo/ and logged the time between the click and the end of the scroll animation. With `autoCoefficient: 1`, it took 1704ms; with  `autoCoefficient: 2`, 857ms; and with  `autoCoefficient: 4`, 434ms.

I'd be happy to take a look and help troubleshoot if you point me to a URL.

**Comment by diegocanal** [comment]
Hi Karl,
I appreciate your help. The URL is http://www.debelareabogados.es/abogados-despidos-madrid/ , you can test it clicking the links of the table of contents within the right sidebar.
Thanks!

**Comment by kswedberg** [comment]
ok, it looks like something else on that page is loading an older version (1.4.9) of the plugin in addition to the new version. The old one is winning. At that point in the git history, `autoCoefficient` was misspelled as `autoCoefficent` (without the second "i"), so if you change the option to the misspelled one and remove the reference to the newer script, it should work. I only suggest that because I'm guessing that smooth-scroll is being loaded by some WordPress plugin or something out of your control. Would be better to remove the old version and just use the new one, of course.

**Comment by diegocanal** [comment]
You are absolutely right. It was the Quform (formerly iPhorm) plugin that was loading the old version, I have already informed the developer in case he wants to update it. Problem solved, now 'autoCoefficient' works as expected.

Thank you!

**Comment by kswedberg** [comment]
You're welcome! Glad we could get it to work.
