### ISSUE TITLE
Easing Functions?

### ISSUE THREAD

**Issue by btn0s** [kswedberg/jquery-smooth-scroll#96]
I can't get any of the jQuery easing functions to work.

I call the `.smoothscroll` as such:
`$('a').smoothScroll({speed: 600});`

and when I try to add in the easing option:
`$('a').smoothScroll({easing: 'easeOutExpo', speed: 600});`

I get an `Uncaught TypeError: jQuery.easing[this.easing] is not a function`

Maybe I'm doing it wrong? I don't think the easing options are even covered in the docs, but I'm thinking it's pretty straight-forward.

**Comment by kswedberg** [comment]
@btn0s : In order to use any of the easing equations (other than "swing" and "linear", which jQuery includes by default), you need to provide an easing plugin. One of these should do the trick:

* [jQuery UI Effects Core](http://jqueryui.com/download/#!version=1.11.4&components=0000000000000000000001000000000000000)
* [jQuery Easing plugin](https://github.com/gdsmith/jquery.easing)

Let me know if you're still having trouble making this work after including one of them.

**Comment by btn0s** [comment]
Ah! Thank you. Now I feel dumb.

**Comment by kswedberg** [comment]
Don't feel dumb. Web development has so many moving parts, it's hard to keep track of everything. Besides, I should probably document the option with a link to the easing plugin.

**Comment by btn0s** [comment]
You're right, thank you!
